### ISSUE TITLE
using RSPM repo

### ISSUE THREAD

**Issue by malcolmbarrett** [grantmcdermott/renv-rspm#1]
Hi Grant -- thanks for the great resource! This is an interesting idea in an area where there is not much guidance, and this was thought-provoking. 

I'm curious what your workflow for establishing RSPM as the repo for the lock file. I was experimenting with this, and I noticed that, after setting `repos` in `options()` as you suggest, I had a mix of CRAN and RSPM packages depending on the state of the package on my computer. Do you simply use this default across the board such that your packages are all from RSPM anyway, or is there a way to tell renv to always use RSPM?

**Comment by grantmcdermott** [comment]
Hey Malcolm, I'm stoked that you found it useful. The issue you raise is something I've encountered myself, so you're not alone. My solution has been twofold:

1. As you've already intimated, I set RSPM as the default repo across the board. My `~/.Rprofile` file contains the line: `options(repos = c(RSPM = "https://packagemanager.rstudio.com/all/latest")) `.

2. Because of the way **renv** caches your libraries &mdash; i.e. it uses a [global cache](https://rstudio.github.io/renv/articles/renv.html#cache-1) for quick installation across projects &mdash; you may still encounter a situation where an "older" cached library from CRAN is being pulled into a new project's lockfile. There are two (sub) strategies here:
   - Do a quick, manual find-and-replace search in your project lockfile. Which is to say, replace all instances of "CRAN" in the `renv.lock` file with "RSPM".
   - The above approach certainly works, but I found it a bid tedious after doing it two or three times. So I ultimately went for the nuclear option of deleting and then rebuilding my global cache.<sup>*</sup> There's a minor one-time cost because **renv** needed to reinstall any libs that were in said global cache, but I haven't had an issue since.

<sup>*</sup> I seem to recall the global cache dir containing separate "CRAN" and "RSPM" sub-dirs, which made this even less dramatic since I only had to delete the former.

**Comment by malcolmbarrett** [comment]
Ah very interesting! That all makes sense and tracks my experience. Thanks for sharing!
